name: build-test-release
on:
  push:
    branches:
      - main
      - arm64-binaries
jobs:
  build-test-release-x86_64:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build all targets x86-64.
        run: |
          make build-all RELEASE_BUILD=true
      - name: Run unit tests across all targets x86-64.
        run: |
          make test-all
      - name: Prepare scenarios to be released.
        run: |
          sudo apt install zip
          zip -r scenarios.zip scenarios
          mv ./bin/ie ./bin/ie-x86_64
      - name: Release Innovation Engine
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: "IE"
          automatic_release_tag: "latest"
          prerelease: true
          files: |
            ./bin/ie-x86_64
            ./scenarios.zip

  build-test-release-aarch64:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Build all target aarch64.
        id: build
        with:
          arch: aarch64
          distro: ubuntu_latest
          run: |
            apt-get update -q && DEBIAN_FRONTEND=noninteractive apt-get install -q -y build-essential git wget
            wget https://go.dev/dl/go1.24.1.linux-arm64.tar.gz
            tar -C /usr/local -xzf go1.24.1.linux-arm64.tar.gz
            export PATH=$PATH:/usr/local/go/bin
            go env
            make build-all RELEASE_BUILD=true
      - name: Run unit tests across all targets aarch64.
        run: |
          make test-all
      - name: Prepare binary to be released.
        run: |
          ls -l ./ && ls -l ./bin/
          mv ./bin/ie ./bin/ie-aarch64
      - name: Release Innovation Engine aarch64
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: "IE"
          automatic_release_tag: "latest"
          prerelease: true
          files: |
            ./bin/ie-aarch64
